### ISSUE TITLE
Proposal: Clean Architecture

### ISSUE THREAD

**Issue by sirolad** [pmbanugo/9ja-munich-meetup#3]
Clean Architecture, is also known as Hexagonal Architecture, Onion Architecture amidst other names. It is an architecture that takes us away from Layered architectures/patterns like MVC. We would look at the lacuna that brought about a need for such architectures and a sample of what it looks like plus its benefits.

**Skill Level**: >= Mid-level
**Speaker**: Surajudeen Akande
**Duration**: 30 mins

**Comment by pmbanugo** [comment]
Thanks @sirolad What's lacuna?

**Comment by sirolad** [comment]
forgive my grammar, lacuna is a gap or the cause for a need
